### ISSUE TITLE
Gradients, mask images, WYSIWYG editor

### ISSUE THREAD

**Issue by uniquejack** [mikke89/libRocket#1]
Hello mate!
I've also added animations and transform features to libRocket long time ago, I've also added duktape for javascript bindings, however your work looks more complete.

I've dropped libRocket only because of a few features that were missing:
- Gradients
- Opacity Image-Masks
And specially the possibility to use these two toghether for very cool effects such as
-webkit-mask-image: radial-gradient(ellipse 60% 45% at 60% 60%, transparent 20%, black 100%);

Are you planning to implement these features in the near future?
Also, is there any WYSIWYG editor for libRocket?

Thanks in advance.

**Comment by mikke89** [comment]
Hey! Right, I remember your name from earlier, thanks for stopping by.

This indeed seems quite powerful, thanks for the suggestion. Right now, I don't see myself having the need for this feature in my current project, so probably not going to implement it. 
However, it should be quite doable. I can see it be implemented with render-to-texture support and some specific shaders, so the user-facing API would need some work. I have thought about it earlier, because then one can implement opacity etc. properly, thus it might have other benefits.

Let me know if you do go ahead and try to get it working.

**Comment by mikke89** [comment]
Oh, and as for your second question, as far as I know there is no WYSIWYG editor, however, it's usually (ideally) compatible html+css so any web WYSIWYG should work for the most common features.
